### ISSUE TITLE
'elm-app test' command fails on newly-created project 

### ISSUE THREAD

**Issue by inactivist** [halfzebra/create-elm-app#61]
If I recall correctly, `elm-app test` worked fine in previous version (with Elm 0.17, create-elm-app 0.1.10).

I upgraded to Elm 0.18.0 and create-elm-app 0.2.0 -- I'm somewhat new to the Elm ecosystem and create-elm-app, so I'm not sure if I've messed up something somewhere.  
```
user@machine:~/elmstuff$ elm-app create test
[snip]
Project is successfully created in `/home/mcurry/m/devel/mine/elmstuff/test`.
[snip]

user@machine:~/elmstuff$ cd test
user@machine:~/elmstuff/test$ elm-app test
I cannot find module 'Tuple'.

Module 'Lazy.List' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
Compilation failed for Main.elm
```

Versions:
- Elm 0.18.0
- create-elm-app@0.2.0
- elm-test@0.18.0
- Node v6.9.1

**Comment by jackfranklin** [comment]
If you `cd tests && elm upgrade` (https://github.com/avh4/elm-upgrade), this will fix it. The latest release, 0.2.1, which is out soon I believe, includes a PR I made to fix the tests out of the box :)

**Comment by halfzebra** [comment]
@inactivist Thanks for the contribution!

Install the latest version of Create Elm App, this issue is already fixed by @jackfranklin in #60 

@jackfranklin we should probably add upgrade instructions to User Guide.

**Comment by flipjs** [comment]
Just downloaded create-elm-app like 15 minutes ago, and had issues too:

```
Compilation failed.

Error in ./src/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
elm-make: Map.!: given key is not an element in the map
 @ ./src/index.js 3:10-31
```

Then I tried this: `cd tests && elm upgrade` but there was an error saying the app is not 0.17 elm project.

I tried running the app again using `elm-app start` and seems to be working now. Im on macOS 10.12.1, node-6.6.0, elm-0.18 and elm-format-0.5.2-alpha.

**Comment by inactivist** [comment]
@flipjs Try deleting tests/elm-stuff and re-running tests.  Don't know why but that worked for me.

**Comment by flipjs** [comment]
@inactivist its all sorted. thanks!

**Comment by jonyardley** [comment]
I am having the same problem as @flipjs here:
* Mac OSX Sierra
* Node => v7.1.0
* Elm => 0.18.0
```
$ elm-app start
Failed to compile.

Error in ./src/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
elm-make: Map.!: given key is not an element in the map
 @ ./src/index.js 3:10-31
```
Any words of advice?

**Comment by halfzebra** [comment]
@jackfranklin Have you tried removing `elm-stuff` and running [elm-upgrade](https://www.npmjs.com/package/elm-upgrade)?

**Comment by jonyardley** [comment]
thanks @halfzebra. That did the trick 💃

**Comment by slashdotdash** [comment]
I encountered the same compilation error as @flipjs after a fresh `npm install create-elm-app -g`. 

It was resolved by running `rm -rf elm-stuff/` and then `elm-app start`.

**Comment by hipertracker** [comment]
**`elm-stuff` just should not be in the repository here**.  It's the source of the problem during creating new project ("elm-make: Map.!: given key is not an element in the map") After deleting `elm-stuff` and running `elm-app start` this folder is created again but this time all is working.

**Comment by jackfranklin** [comment]
@hipertracker I don't think this repository does contain `elm-stuff` ? It gets created when you run `create-elm-app foo` because it runs `elm package install`.
